workers = 2
folder = "/data/archive"
lock_file = "/data/run.lock"
web = "/data/html"
domain = "https://csaf-aggregator"
rate = 10.0
insecure = true
openpgp_private_key = "/config/csaf/private.asc"
openpgp_public_key = "/config/csaf/public.asc"
#passphrase =
write_indices = false

# specification requires at least two providers (default),
# to override for testing, enable:
# allow_single_provider = true

[aggregator]
  # Set if this instance shall be a mirror (aka `aggregator`) or a `lister`.
  # This determines the default value for the entries in [[provider]].
  category = "aggregator"
  name = "Federal agency for cyber security"
  contact_details = "https://csaf-aggregator"
  issuing_authority = "csaf aggregator service"
  namespace = "https://csaf-aggregator"

[[providers]]
  name = "csaf-aggregator"
  domain = "csaf-aggregator"
  create_service_document = true
  write_indices = true
  insecure = true

[[providers]]
  name = "csaf-aggregator"
  domain = "csaf-aggregator"
  insecure = true
  create_service_document = true
  write_indices = true
  