version: '3'
services:
 
  csaf-provider:
    image: csaf_provider:latest
    hostname: csaf-provider
    domainname: csaf-provider
    environment:
      - HOSTNAMES=csaf-provider
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      csaf-network: {}
      
  init-provider:
    image: csaf_uploader:latest
    profiles: [ "run_manually" ]
    depends_on:
      - csaf-provider
    environment:
      OPTIONS: "--config=/data/config-create.ini"
    volumes:
      - ./uploader:/data
    networks:
      csaf-network: {}

  upload-provider:
    image: csaf_uploader:latest
    profiles: [ "run_manually" ]
    depends_on:
      - csaf-provider
    environment:
      OPTIONS: "--config=/data/config-upload.ini ${FILE}"
    volumes:
      - ./uploader:/data
    networks:
      csaf-network: {}

networks:
  csaf-network: {}
